# Generated by Django 6.0.4 on 2026-04-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Playlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musica",
            name="album",
            field=models.CharField(
                blank=True, help_text="Insira o álbum", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="musica",
            name="ano",
            field=models.PositiveIntegerField(
                blank=True, help_text="Insira o ano de lançamento", null=True
            ),
        ),
        migrations.AlterField(
            model_name="musica",
            name="artista",
            field=models.CharField(help_text="Insira o artista", max_length=100),
        ),
        migrations.AlterField(
            model_name="musica",
            name="genero",
            field=models.CharField(
                blank=True, help_text="Insira o gênero", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="musica",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="musica",
            name="titulo",
            field=models.CharField(help_text="Insira o título", max_length=100),
        ),
    ]
