# Generated by Django 6.0.4 on 2026-04-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Playlists", "0004_alter_perfil_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="musica",
            name="imagem_url",
            field=models.URLField(
                blank=True, help_text="URL da capa da música", null=True
            ),
        ),
    ]
