# Generated by Django 6.0.4 on 2026-04-20 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Playlists", "0005_musica_imagem_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="musica_favorita",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Playlists.musica",
                verbose_name="Música favorita",
            ),
        ),
    ]
