# Generated by Django 6.0.4 on 2026-04-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Playlists", "0006_perfil_musica_favorita"),
    ]

    operations = [
        migrations.AddField(
            model_name="musica",
            name="link_musica",
            field=models.URLField(
                blank=True, help_text="Link para ouvir a música", null=True
            ),
        ),
    ]
