# Generated by Django 5.2.13 on 2026-04-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlists', '0006_perfil_musica_favorita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
