# Generated by Django 5.2.13 on 2026-04-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Playlists', '0007_alter_perfil_id'),
        ('Playlists', '0007_musica_link_musica'),
    ]

    operations = [
    ]
